<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GameAssemblyPath>$(MSBuildProjectDirectory)\..\Libs\Managed</GameAssemblyPath>
    <BepInExAssemblyPath>$(MSBuildProjectDirectory)\..\Libs\BepInEx</BepInExAssemblyPath>
    <GamePath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag</GamePath>
    <PluginsPath>$(GamePath)\BepInEx\plugins</PluginsPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameAssemblyPath)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExAssemblyPath)\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameAssemblyPath)\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameAssemblyPath)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GameAssemblyPath)\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameAssemblyPath)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GameAssemblyPath)\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
	  <Reference Include="UnityEngine.IMGUIModule">
		  <HintPath>$(GameAssemblyPath)\UnityEngine.IMGUIModule.dll</HintPath>
	  </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\bundle" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\bundle" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <MakeDir Directories="$(GamePath)\BepInEx\plugins\GorillaTrials" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GamePath)\BepInEx\plugins\GorillaTrials" />
  </Target>

</Project>
